spring:
  datasource:
    url: jdbc:mysql://sql.tomxin.cn:3306/jiandan_house?characterEncoding=utf-8&useSSL=false
    username: jiandan_house
    password: Jcxz1329947@
  jpa:
      show-sql: true
      hibernate:
        ddl-auto: update